name: CI
run-name: ${{ github.actor }} using Rust Continuous Integration

on:
  workflow_dispatch:
  push:
  release:
    types: [created]

permissions:
  contents: read
  pull-requests: read

jobs:
  release:
    name: release-x86
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: "Check out repository: ${{ github.repository }} branch: ${{ github.ref }} by event: ${{ github.event_name }}"
        uses: actions/checkout@master
        with:
          persist-credentials: 'false'

      - name: "Compile and release on server: ${{ runner.os }}"
        uses: rust-build/rust-build.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          EXTRA_FILES: "README.md LICENSE"
          PRE_BUILD: "pre_build.sh"
          POST_BUILD: "test/post_build.sh"
          ARCHIVE_NAME: micro-rust-archive.zip
          UPLOAD_MODE: release
