name: CI
run-name: Continuous Integration
on: push

jobs:
  build:
    name: "Build & Test"
    runs-on: ubuntu-latest

    steps:
      - name: "CI on repository: ${{ github.repository }} branch: ${{ github.ref }} by event: ${{ github.event_name }}"
        run: |
          ls -alR ${{ github.workspace }}

      - name: "Check out repository"
        uses: actions/checkout@master
        with:
          persist-credentials: 'false'

      - name: "Build on ${{ runner.os }} server"
        id: compile
        uses: rust-build/rust-build.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          EXTRA_FILES: "README.md LICENSE"
          PRE_BUILD: "pre_build.sh"
          POST_BUILD: "test/post_build.sh"
          MINIFY: false
          UPLOAD_MODE: none

      - name: List workspace
        run: |
          ls -alR ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-linux-musl
          if-no-files-found: error
          path: |
            assets/
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
