name: CI
run-name: Continuous Integration
on: push

jobs:
  build:
    name: "Build & Test"
    runs-on: ubuntu-latest
    container: rust:1.74-alpine3.18

    steps:
      - name: "CI on repository: ${{ github.repository }} branch: ${{ github.ref }} by event: ${{ github.event_name }}"
        run: |
          ls -alR

      - name: "Check out repository"
        uses: actions/checkout@master
        with:
          persist-credentials: 'false'

      - name: "Build and test on ${{ runner.os }} server"
        run: |
          apk add --no-cache musl-dev protobuf
          cargo build
          cargo test

