name: CI
run-name: ${{ github.actor }} using Rust Build

on:
  workflow_dispatch:
  push:
  release:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Check out repository: ${{ github.repository }} branch: ${{ github.ref }} by event: ${{ github.event_name }}"
        uses: actions/checkout@master
        with:
          persist-credentials: 'false'

      - name: "Build on server: ${{ runner.os }}"
        id: compile
        uses: rust-build/rust-build.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          EXTRA_FILES: "README.md LICENSE"
          PRE_BUILD: "pre_build.sh"
          POST_BUILD: "test/post_build.sh"
          UPLOAD_MODE: none

      - name: List Output
        run: |
          ls -alR ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}

